######################################################################
# Automatically generated by qmake (1.07a) Sat Nov 18 10:14:15 2006
######################################################################

TEMPLATE = app
INCLUDEPATH += . ..
INCLUDEPATH += c:/msys/1.0/local/include

# Input
HEADERS += BSBWidget.h BSBMainWindow.h BSBScrollArea.h
SOURCES += BSBWidget.cpp BSBMainWindow.cpp BSBScrollArea.cpp main.cpp 
LIBS += -lbsb -L.. -L/local/lib 
